apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  # type: ClusterIP  this means only accessible from within the cluster
  # type: NodePort or LoadBalancer to access it from outside the cluster, security implications
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: postgres
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
